name: Acoustic/Input List.xlsx Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Input List/Acoustic/Input List.xlsx'
      - '.github/workflows/acoustic-input-list-workflow.yml'

env:
  ABSOLUTE_EXCEL_FILE_PATH: '' # These will get set in a later step
  ABSOLUTE_PDF_FILE_PATH: '' # These will get set in a later step

jobs:
  postsaveworkflow:
    name: Export image from Excel spreadsheet
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Absolute Path - EXCEL_FILE_PATH
        run: pwsh .github/workflows/lib/Set-Absolute-Path-Variable.ps1 -BasePath "${{ github.workspace }}" -RelativePath "${{ vars.ACOUSTIC_INPUT_LIST_XLSX_PATH }}" -VariableName "ABSOLUTE_EXCEL_FILE_PATH"

      - name: Set Absolute Path - PDF_FILE_PATH
        run: pwsh .github/workflows/lib/Set-Absolute-Path-Variable.ps1 -BasePath "${{ github.workspace }}" -RelativePath "${{ vars.ACOUSTIC_INPUT_LIST_PDF_PATH }}" -VariableName "ABSOLUTE_PDF_FILE_PATH"

      - name: Install Office
        run: choco install office365business --params "'/productid:O365HomePremRetail /exclude:Access Groove Lync OneDrive OneNote Outlook Publisher Word Powerpoint /updates:FALSE /eula:TRUE'"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install Python dependencies
        run: pip install pywin32 ImageGrab pillow

      - name: Export PDF from Excel
        run: python .github/workflows/lib/export-pdf.py "${{ env.ABSOLUTE_EXCEL_FILE_PATH }}" "${{ env.ABSOLUTE_PDF_FILE_PATH }}"

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded 'Input List/Acoustic/Input + Equipment.png'
          commit_user_name: Chad Birch (Automated)
          commit_user_email: chadbirch@hotmail.com
          commit_author: Chad Birch (Automated) <chadbirch@hotmail.com>
          push_options: '--force'
