name: Acoustic/Input List.xlsx Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Input List/Acoustic/Input List.xlsx'

env:
  EXCEL_FILE_PATH: 'Input List/Acoustic/Input List.xlsx'
  PDF_FILE_PATH: 'Input List/Acoustic/Input List.pdf'

jobs:
  postsaveworkflow:
    name: Export image from Excel spreadsheet
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Office
        run: choco install office365business --params "'/productid:ExcelRetail /updates:FALSE'"

      - name: Setup Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Install Python dependencies
        run: pip install pywin32 ImageGrab pillow

      - name: Export PNG from Excel
        run: python .github/workflows/lib/export-pdf.py "${{ env.EXCEL_FILE_PATH }}" "${{ env.PDF_FILE_PATH }}"

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded 'Input List/Acoustic/Input + Equipment.png'
          commit_user_name: Chad Birch (Automated)
          commit_user_email: chadbirch@hotmail.com
          commit_author: Chad Birch (Automated) <chadbirch@hotmail.com>
          push_options: '--force'
