# .github/workflows/full-band-input-list-excel-image-exporter.yml

name: Full Band Input List Excel Image Exporter
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    # paths:
    #   - 'Input List/Full Band/Input List.xlsx'

jobs:
  converttopdf:
    name: Export image from Excel spreadsheet
    runs-on: ubuntu-20.04
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.6.15
        uses: actions/setup-python@v5
        with:
          python-version: '3.6.15'
      - name: Install Python dependencies
        run: pip install excel2img pypiwin32
      - run: ls -la
      - name: Capture image from Excel
        run: python .github/workflows/full-band-input-list-excel-image-exporter.py
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded 'Input List/Full Band/Input + Equipment.png'
          commit_user_name: Chad Birch (Automated)
          commit_user_email: chadbirch@hotmail.com
          commit_author: Chad Birch (Automated) <chadbirch@hotmail.com>
          push_options: '--force'
