name: Rider Workflow
on:
  push:
    branches:
      - main
    paths:
      - 'Rider/Rider.md'
      - '.github/workflows/rider-workflow.yml'

jobs:
  postsaveworkflow:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ${{ vars.RIDER_MARKDOWN_PATH }}
          output_dir: Rider/
          images_dir: Assets
          build_html: false
          image_import: ../Assets

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded '${{ vars.RIDER_PDF_PATH }}'
          commit_user_name: ${{ vars.COMMIT_USER_NAME }}
          commit_user_email: ${{ vars.COMMIT_USER_EMAIL }}
          commit_author: ${{ vars.COMMIT_AUTHOR }}
          push_options: '--force'
