# .github/workflows/rider-workflow/rider-workflow.yml

name: Rider.md Workflow
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'Rider/Rider.md'
      - '.github/workflows/rider-workflow.yml'

env:
  PATH_TO_MARKDOWN: Rider/Rider.md
  PATH_TO_PDF: Rider/Rider.md

jobs:
  postsaveworkflow:
    name: Build PDF
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert Markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ${{ env.PATH_TO_MARKDOWN }}
          output_dir: Rider/
          images_dir: Assets
          build_html: false
          image_import: ../Assets

      - name: Commit changes to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatically uploaded ${{ env.PATH_TO_PDF }}
          commit_user_name: Chad Birch (Automated)
          commit_user_email: chadbirch@hotmail.com
          commit_author: Chad Birch (Automated) <chadbirch@hotmail.com>
          push_options: '--force'
