name: Test

on:
  push:
    branches:
      - main

env:
  EXCEL_FILE_PATH: 'Input List/Full Band/Input List.xlsx'
  INPUT_EQUIPMENT_PNG_PATH: 'Input List/Full Band/Input + Equipment.png'
  PDF_FILE_PATH: 'Input List/Full Band/Input List.pdf'

  ABSOLUTE_EXCEL_FILE_PATH: '' # These will get set in a later step
  ABSOLUTE_INPUT_EQUIPMENT_PNG_PATH: '' # These will get set in a later step
  ABSOLUTE_PDF_FILE_PATH: '' # These will get set in a later step

  INPUT_EQUIPMENT_SHEET: 'Input + Equipment'
  INPUT_EQUIPMENT_RANGE: '$$A$$3:$$I$$35'

jobs:
  postsaveworkflow:
    name: Export image from Excel spreadsheet
    runs-on: windows-latest
    steps:
      - name: PWD
        run: pwd

      - name: Set Absolute Path - EXCEL_FILE_PATH
        run: pwsh ./Set-Absolute-Path-Variable.ps1 -BasePath "${{ github.workspace }}" -RelativePath "${{ env.EXCEL_FILE_PATH }}" -VariableName "ABSOLUTE_EXCEL_FILE_PATH"
        working-directory: .github\workflows\lib\

      # - name: Test Script
      #   run: |
      #     echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
      #     echo "EXCEL_FILE_PATH: ${{ env.EXCEL_FILE_PATH }}"
      #     echo "ABSOLUTE_EXCEL_FILE_PATH: ${{ github.workspace }}\${{ env.EXCEL_FILE_PATH }}"

      #     echo "ABSOLUTE_EXCEL_FILE_PATH=${{ github.workspace }}\${{ env.EXCEL_FILE_PATH }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Test Script 2
        run: |
          echo "ABSOLUTE_EXCEL_FILE_PATH: ${{ env.ABSOLUTE_EXCEL_FILE_PATH }}"

      - name: Test Script 3
        run: |
          cat $Env:GITHUB_ENV